version: '3.8'
services:
  db:
    image: postgres:14.0-alpine
    container_name: fos-db
    volumes:
      - fos_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_ADDITIONAL_DATABASES}" ]
      interval: 3s
      timeout: 10s
      retries: 5
    command: postgres -c listen_addresses='*'
volumes:
  fos_data:
    driver: local